# Generated by Django 4.2.3 on 2023-08-26 22:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Name')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('deletion', models.DateTimeField(blank=True, null=True, verbose_name='Delete?')),
                ('category_parent_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='torrent.category', verbose_name='Parent category')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='ExternalTorrent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, max_length=2000, null=True, verbose_name='URL of official website')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Project name')),
                ('is_active', models.BooleanField(default=False, verbose_name='Show in the front end')),
                ('description', models.TextField(blank=True, default='', null=True, verbose_name='Description of project')),
                ('website_url', models.CharField(blank=True, max_length=2000, null=True, verbose_name='URL of official website')),
                ('website_url_download', models.CharField(blank=True, max_length=2000, verbose_name='URL of official download page')),
                ('website_url_repo', models.CharField(blank=True, max_length=2000, verbose_name='URL of repository')),
                ('image', models.ImageField(blank=True, null=True, upload_to='img/project/original/')),
                ('mini_image', models.ImageField(blank=True, upload_to='img/project/mini/')),
                ('small_image', models.ImageField(blank=True, upload_to='img/project/small/')),
                ('medium_image', models.ImageField(blank=True, upload_to='img/project/medium/')),
                ('large_image', models.ImageField(blank=True, upload_to='img/project/large/')),
            ],
        ),
        migrations.CreateModel(
            name='Torrent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info_hash', models.CharField(max_length=40, unique=True, verbose_name='SHA1 of torrent')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('size', models.PositiveBigIntegerField(default=0, verbose_name='Size')),
                ('pieces', models.IntegerField(default=1, verbose_name='Number of piece')),
                ('piece_size', models.IntegerField(default=0, verbose_name='Piece size in byte')),
                ('magnet', models.TextField(default='NONAME', verbose_name='Magnet URI')),
                ('torrent_filename', models.CharField(default='NONAME', max_length=128, verbose_name='Torrent file name')),
                ('comment', models.CharField(default='NONAME', max_length=256, verbose_name='Comment')),
                ('file_list', models.TextField(default='NONAME', verbose_name='List of files')),
                ('file_nbr', models.IntegerField(default=1, verbose_name='Number of file')),
                ('is_active', models.BooleanField(default=False, verbose_name='Show in the front end')),
                ('is_bitiso', models.BooleanField(default=True, verbose_name='Created by bitiso ?')),
                ('description', models.TextField(blank=True, default='', null=True, verbose_name='Description')),
                ('website_url', models.CharField(blank=True, max_length=2000, null=True, verbose_name='URL of official website')),
                ('website_url_download', models.CharField(blank=True, max_length=2000, verbose_name='URL of official download page')),
                ('website_url_repo', models.CharField(blank=True, max_length=2000, verbose_name='URL of repository')),
                ('version', models.CharField(blank=True, max_length=16, verbose_name='Version of the software')),
                ('gpg_signature', models.FileField(blank=True, upload_to='torrent/')),
                ('metainfo_file', models.FileField(blank=True, upload_to='torrent/')),
                ('hash_signature', models.CharField(blank=True, max_length=128, null=True, verbose_name='Any hash signature')),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('deletion', models.DateTimeField(blank=True, null=True, verbose_name='Delete?')),
                ('seed', models.IntegerField(default=0, verbose_name='Number of seed')),
                ('leech', models.IntegerField(default=0, verbose_name='Number of leech')),
                ('dl_number', models.IntegerField(default=0, verbose_name='Number of download')),
                ('dl_completed', models.IntegerField(default=0, verbose_name='Number of completed')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='torrent.category', verbose_name='Category')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='torrent.project', verbose_name='Project')),
            ],
            options={
                'verbose_name': 'Torrent',
                'verbose_name_plural': 'Torrents',
            },
        ),
        migrations.CreateModel(
            name='Tracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='TrackerStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=0, verbose_name='Announce level')),
                ('seed', models.IntegerField(default=0, verbose_name='Number of seed')),
                ('leech', models.IntegerField(default=0, verbose_name='Number of leech')),
                ('torrent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='torrent.torrent')),
                ('tracker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='torrent.tracker')),
            ],
        ),
        migrations.AddField(
            model_name='torrent',
            name='trackers',
            field=models.ManyToManyField(through='torrent.TrackerStat', to='torrent.tracker'),
        ),
        migrations.AddField(
            model_name='torrent',
            name='uploader',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Uploader'),
        ),
    ]
