# Generated by Django 4.0.1 on 2022-01-17 22:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('torrent', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='category',
            name='ix_category_categoryParentId',
        ),
        migrations.RemoveIndex(
            model_name='torrent',
            name='ix_torrent_categoryId',
        ),
        migrations.RemoveIndex(
            model_name='torrent',
            name='ix_torrent_uploader',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='categoryParentId',
            new_name='category_parent_id',
        ),
        migrations.RenameField(
            model_name='torrent',
            old_name='categoryId',
            new_name='category_id',
        ),
        migrations.RenameField(
            model_name='torrent',
            old_name='dlCompleted',
            new_name='dl_completed',
        ),
        migrations.RenameField(
            model_name='torrent',
            old_name='dlNumber',
            new_name='dl_number',
        ),
        migrations.RenameField(
            model_name='torrent',
            old_name='nbPiece',
            new_name='nb_piece',
        ),
        migrations.RenameField(
            model_name='torrent',
            old_name='sizePiece',
            new_name='size_piece',
        ),
        migrations.RenameField(
            model_name='torrent',
            old_name='sizePieceUnit',
            new_name='size_piece_unit',
        ),
        migrations.RenameField(
            model_name='torrent',
            old_name='sizeUnit',
            new_name='size_unit',
        ),
        migrations.RenameField(
            model_name='torrent',
            old_name='torrentFileName',
            new_name='torrent_filename',
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='torrent',
            name='gpg_signature',
            field=models.FileField(blank=True, upload_to='signature/'),
        ),
        migrations.AddField(
            model_name='torrent',
            name='metainfo_file',
            field=models.FileField(blank=True, upload_to='torrent/'),
        ),
        migrations.AddField(
            model_name='torrent',
            name='version',
            field=models.CharField(blank=True, max_length=16, verbose_name='Version of the software'),
        ),
        migrations.AddField(
            model_name='torrent',
            name='website_url',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='URL of official website'),
        ),
        migrations.AddField(
            model_name='torrent',
            name='website_url_download',
            field=models.CharField(blank=True, max_length=2000, verbose_name='URL of official download page'),
        ),
        migrations.AddField(
            model_name='torrent',
            name='website_url_repo',
            field=models.CharField(blank=True, max_length=2000, verbose_name='URL of repository'),
        ),
        migrations.AlterField(
            model_name='torrent',
            name='description',
            field=models.CharField(blank=True, default='', max_length=8192, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='torrent',
            name='uploader',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Uploader'),
        ),
    ]
