# Generated by Django 4.2.3 on 2023-08-04 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('torrent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Project name')),
                ('description', models.TextField(blank=True, default='', null=True, verbose_name='Description of project')),
                ('website_url', models.CharField(blank=True, max_length=2000, null=True, verbose_name='URL of official website')),
                ('website_url_download', models.CharField(blank=True, max_length=2000, verbose_name='URL of official download page')),
                ('website_url_repo', models.CharField(blank=True, max_length=2000, verbose_name='URL of repository')),
            ],
        ),
        migrations.RemoveField(
            model_name='tracker',
            name='name',
        ),
        migrations.AddField(
            model_name='torrent',
            name='project_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='torrent.project', verbose_name='Project'),
        ),
    ]
