# Generated by Django 4.0.1 on 2022-02-01 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torrent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='torrent',
            name='hash_signature',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Any hash signature'),
        ),
        migrations.AlterField(
            model_name='torrent',
            name='description',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Description'),
        ),
    ]
