# Generated by Django 4.0.1 on 2022-01-21 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torrent', '0002_remove_category_ix_category_categoryparentid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='torrent',
            old_name='nb_piece',
            new_name='pieces',
        ),
        migrations.RemoveField(
            model_name='torrent',
            name='size_piece',
        ),
        migrations.RemoveField(
            model_name='torrent',
            name='size_piece_unit',
        ),
        migrations.RemoveField(
            model_name='torrent',
            name='size_unit',
        ),
        migrations.AddField(
            model_name='torrent',
            name='magnet',
            field=models.CharField(default='NONAME', max_length=256, verbose_name='Magnet URI'),
        ),
        migrations.AddField(
            model_name='torrent',
            name='piece_size',
            field=models.IntegerField(default=0, verbose_name='Piece size in byte'),
        ),
        migrations.AlterField(
            model_name='torrent',
            name='hash',
            field=models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='SHA1 of torrent'),
        ),
        migrations.AlterField(
            model_name='torrent',
            name='size',
            field=models.IntegerField(default=0, verbose_name='Size'),
        ),
    ]
