# Generated by Django 4.2.3 on 2023-08-04 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('torrent', '0002_project_remove_tracker_name_torrent_project_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='torrent',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='torrent',
            old_name='project_id',
            new_name='project',
        ),
    ]
