# Generated by Django 4.2.3 on 2023-08-05 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torrent', '0003_rename_category_id_torrent_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadTorrent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_list', models.TextField()),
            ],
        ),
    ]
