# Generated by Django 4.0.1 on 2022-01-24 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torrent', '0003_rename_nb_piece_torrent_pieces_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='torrent',
            old_name='hash',
            new_name='info_hash',
        ),
        migrations.RenameField(
            model_name='torrentstatsl',
            old_name='hash',
            new_name='info_hash',
        ),
        migrations.AlterField(
            model_name='torrent',
            name='gpg_signature',
            field=models.FileField(blank=True, upload_to='torrent/'),
        ),
    ]
