# Generated by Django 4.2.3 on 2023-08-05 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torrent', '0004_downloadtorrent'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExistingTorrent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, max_length=2000, null=True, verbose_name='URL of official website')),
            ],
        ),
        migrations.RenameModel(
            old_name='DownloadTorrent',
            new_name='ListeIntermediaire',
        ),
        migrations.RenameField(
            model_name='listeintermediaire',
            old_name='data_list',
            new_name='donnees',
        ),
    ]
