# Generated by Django 4.0.1 on 2022-01-25 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torrent', '0004_rename_hash_torrent_info_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='torrent',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Show in the front end'),
        ),
    ]
