# Generated by Django 4.2.3 on 2023-08-06 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('torrent', '0005_existingtorrent_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listeintermediaire',
            old_name='donnees',
            new_name='url',
        ),
    ]
