# Generated by Django 4.0.1 on 2022-01-27 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torrent', '0005_torrent_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='torrent',
            name='comment',
            field=models.CharField(default='NONAME', max_length=256, verbose_name='Comment'),
        ),
        migrations.AddField(
            model_name='torrent',
            name='trackers',
            field=models.ManyToManyField(to='torrent.Tracker'),
        ),
    ]
