# Generated by Django 4.0.1 on 2022-01-27 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torrent', '0007_tracker_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='torrent',
            name='file_list',
            field=models.TextField(default='NONAME', verbose_name='List of files'),
        ),
    ]
