# Generated by Django 4.2.3 on 2023-08-08 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('torrent', '0007_configuration'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExistingTorrent',
            new_name='ExternalTorrent',
        ),
        migrations.DeleteModel(
            name='Configuration',
        ),
        migrations.DeleteModel(
            name='ListeIntermediaire',
        ),
    ]
