# Generated by Django 4.2.3 on 2023-08-14 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torrent', '0008_rename_existingtorrent_externaltorrent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='img/project/'),
        ),
        migrations.AddField(
            model_name='project',
            name='large_image',
            field=models.ImageField(blank=True, upload_to='img/project/large/'),
        ),
        migrations.AddField(
            model_name='project',
            name='medium_image',
            field=models.ImageField(blank=True, upload_to='img/project/medium/'),
        ),
        migrations.AddField(
            model_name='project',
            name='original_image',
            field=models.ImageField(blank=True, null=True, upload_to='img/project/original/'),
        ),
        migrations.AddField(
            model_name='project',
            name='small_image',
            field=models.ImageField(blank=True, upload_to='img/project/small/'),
        ),
    ]
