# Generated by Django 4.0.1 on 2022-01-27 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torrent', '0008_torrent_file_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='torrent',
            name='file_nbr',
            field=models.IntegerField(default=1, verbose_name='Number of file'),
        ),
    ]
