# Generated by Django 4.2.3 on 2023-08-14 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torrent', '0009_project_image_project_large_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='original_image',
        ),
        migrations.AddField(
            model_name='project',
            name='mini_image',
            field=models.ImageField(blank=True, upload_to='img/project/mini/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='img/project/original/'),
        ),
    ]
