# Generated by Django 4.2.3 on 2023-08-23 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torrent', '0011_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Show in the front end'),
        ),
    ]
