# Generated by Django 4.0.1 on 2022-01-31 15:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, verbose_name='Name')),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('deletion', models.DateTimeField(blank=True, null=True, verbose_name='Delete?')),
                ('category_parent_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='torrent.category', verbose_name='Parent category')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Tracker',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='NONAME', max_length=32)),
                ('url', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Torrent',
            fields=[
                ('info_hash', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='SHA1 of torrent')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('size', models.IntegerField(default=0, verbose_name='Size')),
                ('pieces', models.IntegerField(default=1, verbose_name='Number of piece')),
                ('piece_size', models.IntegerField(default=0, verbose_name='Piece size in byte')),
                ('magnet', models.CharField(default='NONAME', max_length=2000, verbose_name='Magnet URI')),
                ('torrent_filename', models.CharField(default='NONAME', max_length=128, verbose_name='Torrent file name')),
                ('comment', models.CharField(default='NONAME', max_length=256, verbose_name='Comment')),
                ('file_list', models.TextField(default='NONAME', verbose_name='List of files')),
                ('file_nbr', models.IntegerField(default=1, verbose_name='Number of file')),
                ('is_active', models.BooleanField(default=False, verbose_name='Show in the front end')),
                ('is_bitiso', models.BooleanField(default=True, verbose_name='Created by bitiso ?')),
                ('description', models.CharField(blank=True, default='', max_length=8192, null=True, verbose_name='Description')),
                ('website_url', models.CharField(blank=True, max_length=2000, null=True, verbose_name='URL of official website')),
                ('website_url_download', models.CharField(blank=True, max_length=2000, verbose_name='URL of official download page')),
                ('website_url_repo', models.CharField(blank=True, max_length=2000, verbose_name='URL of repository')),
                ('version', models.CharField(blank=True, max_length=16, verbose_name='Version of the software')),
                ('gpg_signature', models.FileField(blank=True, upload_to='torrent/')),
                ('metainfo_file', models.FileField(blank=True, upload_to='torrent/')),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('deletion', models.DateTimeField(blank=True, null=True, verbose_name='Delete?')),
                ('seed', models.IntegerField(default=0, verbose_name='Number of seed')),
                ('leech', models.IntegerField(default=0, verbose_name='Number of leech')),
                ('dl_number', models.IntegerField(default=0, verbose_name='Number of download')),
                ('dl_completed', models.IntegerField(default=0, verbose_name='Number of completed')),
                ('category_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='torrent.category', verbose_name='Category')),
                ('trackers', models.ManyToManyField(to='torrent.Tracker')),
                ('uploader', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Uploader')),
            ],
            options={
                'verbose_name': 'Torrent',
                'verbose_name_plural': 'Torrents',
            },
        ),
    ]
