# Generated by Django 5.1.2 on 2024-10-19 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_page_content_en_page_content_fr_page_title_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='is_homepage',
            field=models.BooleanField(default=False, verbose_name='Is Homepage'),
        ),
    ]
