# Generated by Django 5.1.3 on 2024-11-27 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torrents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='website_url_download',
            field=models.URLField(blank=True, max_length=2000, null=True, verbose_name='Download page URL'),
        ),
    ]
