# Generated by Django 5.1.3 on 2024-11-27 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torrents', '0002_alter_project_website_url_download'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='torrents.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='project',
            name='large_image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='img/project/large/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='medium_image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='img/project/medium/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='mini_image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='img/project/mini/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='small_image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='img/project/small/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='website_url_repo',
            field=models.URLField(blank=True, max_length=2000, null=True, verbose_name='Repository URL'),
        ),
    ]
