# Generated by Django 5.1.2 on 2024-11-05 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torrents', '0006_alter_project_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='torrent',
            name='gpg_signature_path',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='GPG signature path'),
        ),
        migrations.AddField(
            model_name='torrent',
            name='is_signed',
            field=models.BooleanField(default=False, verbose_name='Is signed'),
        ),
        migrations.AddField(
            model_name='torrent',
            name='original_file_path',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Original Torrent path'),
        ),
        migrations.AddField(
            model_name='torrent',
            name='processed_file_path',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Processed Torrent path'),
        ),
    ]
