# Generated by Django 5.1.2 on 2024-11-11 17:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torrents', '0007_torrent_gpg_signature_path_torrent_is_signed_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='torrent',
            name='original_file_path',
        ),
        migrations.RemoveField(
            model_name='torrent',
            name='processed_file_path',
        ),
        migrations.RemoveField(
            model_name='torrent',
            name='torrent_filename',
        ),
        migrations.AddField(
            model_name='torrent',
            name='architecture',
            field=models.CharField(blank=True, choices=[('i386', 'i386'), ('amd64', 'amd64'), ('arm64', 'ARM64'), ('arm', 'ARM')], max_length=10, null=True, verbose_name='Architecture'),
        ),
        migrations.AddField(
            model_name='torrent',
            name='os',
            field=models.CharField(blank=True, choices=[('linux', 'Linux'), ('windows', 'Windows'), ('macos', 'MacOS'), ('bsd', 'BSD')], max_length=10, null=True, verbose_name='Operating System'),
        ),
        migrations.AddField(
            model_name='torrent',
            name='torrent_file_path',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Torrent file path'),
        ),
        migrations.AlterField(
            model_name='torrent',
            name='comment',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='torrent',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='torrent',
            name='file_list',
            field=models.TextField(blank=True, null=True, verbose_name='List of files'),
        ),
        migrations.AlterField(
            model_name='torrent',
            name='magnet',
            field=models.TextField(blank=True, null=True, verbose_name='Magnet URI'),
        ),
        migrations.AlterField(
            model_name='torrent',
            name='slug',
            field=models.SlugField(blank=True, max_length=128, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='torrent',
            name='version',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Version of the software'),
        ),
        migrations.AlterField(
            model_name='torrent',
            name='website_url_download',
            field=models.URLField(blank=True, max_length=2000, null=True, verbose_name='Download page URL'),
        ),
        migrations.AlterField(
            model_name='torrent',
            name='website_url_repo',
            field=models.URLField(blank=True, max_length=2000, null=True, verbose_name='Repository URL'),
        ),
        migrations.AddIndex(
            model_name='torrent',
            index=models.Index(fields=['info_hash'], name='torrents_to_info_ha_c9cc27_idx'),
        ),
        migrations.AddIndex(
            model_name='torrent',
            index=models.Index(fields=['created_at'], name='torrents_to_created_062a65_idx'),
        ),
        migrations.AddIndex(
            model_name='torrent',
            index=models.Index(fields=['updated_at'], name='torrents_to_updated_2cd42e_idx'),
        ),
        migrations.AddIndex(
            model_name='torrent',
            index=models.Index(fields=['is_active'], name='torrents_to_is_acti_977b82_idx'),
        ),
        migrations.AddIndex(
            model_name='torrent',
            index=models.Index(fields=['category'], name='torrents_to_categor_3cbfc1_idx'),
        ),
    ]
