# Generated by Django 5.1.2 on 2024-11-14 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('torrents', '0011_remove_torrent_gpg_signature_path_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='torrent',
            name='torrent_file_path',
        ),
    ]
