# Generated by Django 5.1.2 on 2024-11-14 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torrents', '0012_remove_torrent_torrent_file_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description_en',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='category',
            name='description_fr',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='license',
            name='description_en',
            field=models.TextField(blank=True, default='', null=True, verbose_name='License description'),
        ),
        migrations.AddField(
            model_name='license',
            name='description_fr',
            field=models.TextField(blank=True, default='', null=True, verbose_name='License description'),
        ),
        migrations.AddField(
            model_name='project',
            name='description_en',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Description of project'),
        ),
        migrations.AddField(
            model_name='project',
            name='description_fr',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Description of project'),
        ),
        migrations.AddField(
            model_name='torrent',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='torrent',
            name='description_fr',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
