# Generated by Django 5.1.2 on 2024-11-15 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torrents', '0014_license_website_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='website_url_en',
            field=models.URLField(blank=True, max_length=2000, null=True, verbose_name='Official website URL'),
        ),
        migrations.AddField(
            model_name='license',
            name='website_url_fr',
            field=models.URLField(blank=True, max_length=2000, null=True, verbose_name='Official website URL'),
        ),
    ]
