# Generated by Django 5.1.2 on 2024-11-19 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('torrents', '0021_rename_last_try_date_tracker_last_try'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tracker',
            name='failed_attempts',
        ),
    ]
