# Generated by Django 5.1.2 on 2024-11-04 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torrents', '0003_license_alter_project_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Description'),
        ),
    ]
