# Generated by Django 5.1.2 on 2024-11-19 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torrents', '0016_tracker_is_scrapable_tracker_last_try_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracker',
            name='failed_attempts',
            field=models.PositiveIntegerField(default=0, help_text='Number of consecutive failed scrape attempts.'),
        ),
        migrations.AddField(
            model_name='tracker',
            name='is_reachable',
            field=models.BooleanField(default=True, help_text='Indicates whether the tracker is currently reachable.'),
        ),
        migrations.AddField(
            model_name='tracker',
            name='last_successful_scrape',
            field=models.DateTimeField(blank=True, help_text='The most recent date when scraping succeeded.', null=True),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='is_scrapable',
            field=models.BooleanField(default=True, help_text='Indicates whether the tracker supports scraping.'),
        ),
    ]
