# Generated by Django 5.1.2 on 2024-11-19 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torrents', '0019_trackerstat_last_scrape_attempt_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tracker',
            name='last_successful_scrape',
        ),
        migrations.AddField(
            model_name='tracker',
            name='last_seen',
            field=models.DateTimeField(blank=True, help_text='The last date when the tracker was successfully contacted (network-level reachability).', null=True),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='failed_attempts',
            field=models.PositiveIntegerField(default=0, help_text='Number of consecutive failed attempts to contact or scrape the tracker.'),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='is_scrapable',
            field=models.BooleanField(default=True, help_text='Indicates whether the tracker supports scraping (managed manually or via analysis).'),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='last_try_date',
            field=models.DateTimeField(blank=True, help_text='The most recent attempt to contact the tracker (network-level or scrape).', null=True),
        ),
    ]
