# Generated by Django 5.1.2 on 2024-11-19 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('torrents', '0020_remove_tracker_last_successful_scrape_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tracker',
            old_name='last_try_date',
            new_name='last_try',
        ),
    ]
