# Generated by Django 5.1.2 on 2024-11-19 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torrents', '0022_remove_tracker_failed_attempts'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracker',
            name='is_reachable_mode',
            field=models.CharField(choices=[('automatic', 'Automatic'), ('manual', 'Manual')], default='automatic', help_text='Indicates whether the is_reachable field is managed automatically or manually.', max_length=10),
        ),
        migrations.AddField(
            model_name='tracker',
            name='is_scrapable_mode',
            field=models.CharField(choices=[('automatic', 'Automatic'), ('manual', 'Manual')], default='automatic', help_text='Indicates whether the is_scrapable field is managed automatically or manually.', max_length=10),
        ),
    ]
