# Generated by Django 5.1.2 on 2024-10-24 10:32

import core.user_profiles.utils
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('torrents', '0002_remove_torrent_uploader_category_updated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BitisoUserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, verbose_name='Bio')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to=core.user_profiles.utils.PathAndRename('profile_pics/'), validators=[core.user_profiles.utils.validate_image_type, core.user_profiles.utils.validate_file_size], verbose_name='Profile Picture')),
                ('favorite_torrents', models.ManyToManyField(blank=True, to='torrents.torrent')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bitiso User Profile',
                'verbose_name_plural': 'Bitiso User Profiles',
            },
        ),
    ]
