# Generated by Django 5.1.2 on 2024-11-04 22:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitiso_user_profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bitisouserprofile',
            options={},
        ),
        migrations.RemoveField(
            model_name='bitisouserprofile',
            name='favorite_torrents',
        ),
        migrations.AlterField(
            model_name='bitisouserprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bitisouserprofile', to=settings.AUTH_USER_MODEL),
        ),
    ]
