# Generated by Django 5.1.2 on 2024-10-20 21:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/', verbose_name='Profile Picture')),
                ('bio', models.TextField(blank=True, verbose_name='Bio')),
                ('social_links', models.JSONField(blank=True, null=True, verbose_name='Social Links')),
                ('privacy_settings', models.JSONField(blank=True, null=True, verbose_name='Privacy Settings')),
                ('notification_preferences', models.JSONField(blank=True, null=True, verbose_name='Notification Preferences')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
