# Generated by Django 4.0.1 on 2022-02-01 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torrent', '0002_torrent_hash_signature_alter_torrent_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='torrent',
            name='magnet',
            field=models.TextField(default='NONAME', verbose_name='Magnet URI'),
        ),
    ]
